//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/InputActions/PlayersInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayersInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayersInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayersInputActions"",
    ""maps"": [
        {
            ""name"": ""Player1"",
            ""id"": ""fa0b9731-3d90-4138-b0b2-593445d6453a"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Button"",
                    ""id"": ""1950e601-d319-42aa-8a1c-a8fa8d7ce99b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""UseSpecialAbility"",
                    ""type"": ""Button"",
                    ""id"": ""04e008e0-4d84-442b-8f9a-0852a7e1c218"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BackToCheckpoint"",
                    ""type"": ""Button"",
                    ""id"": ""4dccc444-13ec-45be-87e5-905ead0d66ac"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0d06b00c-0d32-4a9f-a00f-49b6bbda4c67"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""502f0936-25ca-4dad-9150-ce76278fab5f"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d2dc360c-c9eb-4f0e-85dd-bc8fce96c7e0"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3c01315c-6459-4004-a90f-348a5682cac8"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""be5750ca-a0c4-44a2-a905-6368e99022f3"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseSpecialAbility"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""54266177-35ab-497f-ae2f-026d954fd20e"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BackToCheckpoint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Player2"",
            ""id"": ""14c09f87-bbbc-45de-94fc-7ce34346a7dc"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Button"",
                    ""id"": ""2ea84bc6-aa9b-4c40-bf43-a1e4eea29514"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseSpecialAbility"",
                    ""type"": ""Button"",
                    ""id"": ""615501ce-57d2-473d-b165-281a46602c01"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BackToCheckpoint"",
                    ""type"": ""Button"",
                    ""id"": ""4a816e80-2d80-4b48-b9f8-50cf95e37090"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8b4659b2-f0df-4d9c-9968-5e17c841c0c9"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a05c9726-455a-4b18-abc8-918fdd68bbf7"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""392b02fb-1d3b-4e4c-b588-00ec80795ad1"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""af53eab7-f44b-4b70-99c3-7499b4021b73"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""96507ccb-8f18-4ff1-8254-ad9f83ac5dfd"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseSpecialAbility"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ec6e98d1-cf10-496d-9324-9a55b50de815"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BackToCheckpoint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""59258069-b652-4383-af81-caab40b23b28"",
            ""actions"": [
                {
                    ""name"": ""ChangePausePanelVisibility"",
                    ""type"": ""Button"",
                    ""id"": ""810e56b2-0d8f-44ac-90ae-05a93ffd8096"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e999b22c-bc11-4337-8b51-3330834b85ce"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangePausePanelVisibility"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player1
        m_Player1 = asset.FindActionMap("Player1", throwIfNotFound: true);
        m_Player1_Move = m_Player1.FindAction("Move", throwIfNotFound: true);
        m_Player1_UseSpecialAbility = m_Player1.FindAction("UseSpecialAbility", throwIfNotFound: true);
        m_Player1_BackToCheckpoint = m_Player1.FindAction("BackToCheckpoint", throwIfNotFound: true);
        // Player2
        m_Player2 = asset.FindActionMap("Player2", throwIfNotFound: true);
        m_Player2_Move = m_Player2.FindAction("Move", throwIfNotFound: true);
        m_Player2_UseSpecialAbility = m_Player2.FindAction("UseSpecialAbility", throwIfNotFound: true);
        m_Player2_BackToCheckpoint = m_Player2.FindAction("BackToCheckpoint", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_ChangePausePanelVisibility = m_UI.FindAction("ChangePausePanelVisibility", throwIfNotFound: true);
    }

    ~@PlayersInputActions()
    {
        UnityEngine.Debug.Assert(!m_Player1.enabled, "This will cause a leak and performance issues, PlayersInputActions.Player1.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_Player2.enabled, "This will cause a leak and performance issues, PlayersInputActions.Player2.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_UI.enabled, "This will cause a leak and performance issues, PlayersInputActions.UI.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player1
    private readonly InputActionMap m_Player1;
    private List<IPlayer1Actions> m_Player1ActionsCallbackInterfaces = new List<IPlayer1Actions>();
    private readonly InputAction m_Player1_Move;
    private readonly InputAction m_Player1_UseSpecialAbility;
    private readonly InputAction m_Player1_BackToCheckpoint;
    public struct Player1Actions
    {
        private @PlayersInputActions m_Wrapper;
        public Player1Actions(@PlayersInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Player1_Move;
        public InputAction @UseSpecialAbility => m_Wrapper.m_Player1_UseSpecialAbility;
        public InputAction @BackToCheckpoint => m_Wrapper.m_Player1_BackToCheckpoint;
        public InputActionMap Get() { return m_Wrapper.m_Player1; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Player1Actions set) { return set.Get(); }
        public void AddCallbacks(IPlayer1Actions instance)
        {
            if (instance == null || m_Wrapper.m_Player1ActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Player1ActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @UseSpecialAbility.started += instance.OnUseSpecialAbility;
            @UseSpecialAbility.performed += instance.OnUseSpecialAbility;
            @UseSpecialAbility.canceled += instance.OnUseSpecialAbility;
            @BackToCheckpoint.started += instance.OnBackToCheckpoint;
            @BackToCheckpoint.performed += instance.OnBackToCheckpoint;
            @BackToCheckpoint.canceled += instance.OnBackToCheckpoint;
        }

        private void UnregisterCallbacks(IPlayer1Actions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @UseSpecialAbility.started -= instance.OnUseSpecialAbility;
            @UseSpecialAbility.performed -= instance.OnUseSpecialAbility;
            @UseSpecialAbility.canceled -= instance.OnUseSpecialAbility;
            @BackToCheckpoint.started -= instance.OnBackToCheckpoint;
            @BackToCheckpoint.performed -= instance.OnBackToCheckpoint;
            @BackToCheckpoint.canceled -= instance.OnBackToCheckpoint;
        }

        public void RemoveCallbacks(IPlayer1Actions instance)
        {
            if (m_Wrapper.m_Player1ActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayer1Actions instance)
        {
            foreach (var item in m_Wrapper.m_Player1ActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Player1ActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public Player1Actions @Player1 => new Player1Actions(this);

    // Player2
    private readonly InputActionMap m_Player2;
    private List<IPlayer2Actions> m_Player2ActionsCallbackInterfaces = new List<IPlayer2Actions>();
    private readonly InputAction m_Player2_Move;
    private readonly InputAction m_Player2_UseSpecialAbility;
    private readonly InputAction m_Player2_BackToCheckpoint;
    public struct Player2Actions
    {
        private @PlayersInputActions m_Wrapper;
        public Player2Actions(@PlayersInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Player2_Move;
        public InputAction @UseSpecialAbility => m_Wrapper.m_Player2_UseSpecialAbility;
        public InputAction @BackToCheckpoint => m_Wrapper.m_Player2_BackToCheckpoint;
        public InputActionMap Get() { return m_Wrapper.m_Player2; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Player2Actions set) { return set.Get(); }
        public void AddCallbacks(IPlayer2Actions instance)
        {
            if (instance == null || m_Wrapper.m_Player2ActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Player2ActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @UseSpecialAbility.started += instance.OnUseSpecialAbility;
            @UseSpecialAbility.performed += instance.OnUseSpecialAbility;
            @UseSpecialAbility.canceled += instance.OnUseSpecialAbility;
            @BackToCheckpoint.started += instance.OnBackToCheckpoint;
            @BackToCheckpoint.performed += instance.OnBackToCheckpoint;
            @BackToCheckpoint.canceled += instance.OnBackToCheckpoint;
        }

        private void UnregisterCallbacks(IPlayer2Actions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @UseSpecialAbility.started -= instance.OnUseSpecialAbility;
            @UseSpecialAbility.performed -= instance.OnUseSpecialAbility;
            @UseSpecialAbility.canceled -= instance.OnUseSpecialAbility;
            @BackToCheckpoint.started -= instance.OnBackToCheckpoint;
            @BackToCheckpoint.performed -= instance.OnBackToCheckpoint;
            @BackToCheckpoint.canceled -= instance.OnBackToCheckpoint;
        }

        public void RemoveCallbacks(IPlayer2Actions instance)
        {
            if (m_Wrapper.m_Player2ActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayer2Actions instance)
        {
            foreach (var item in m_Wrapper.m_Player2ActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Player2ActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public Player2Actions @Player2 => new Player2Actions(this);

    // UI
    private readonly InputActionMap m_UI;
    private List<IUIActions> m_UIActionsCallbackInterfaces = new List<IUIActions>();
    private readonly InputAction m_UI_ChangePausePanelVisibility;
    public struct UIActions
    {
        private @PlayersInputActions m_Wrapper;
        public UIActions(@PlayersInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @ChangePausePanelVisibility => m_Wrapper.m_UI_ChangePausePanelVisibility;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void AddCallbacks(IUIActions instance)
        {
            if (instance == null || m_Wrapper.m_UIActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UIActionsCallbackInterfaces.Add(instance);
            @ChangePausePanelVisibility.started += instance.OnChangePausePanelVisibility;
            @ChangePausePanelVisibility.performed += instance.OnChangePausePanelVisibility;
            @ChangePausePanelVisibility.canceled += instance.OnChangePausePanelVisibility;
        }

        private void UnregisterCallbacks(IUIActions instance)
        {
            @ChangePausePanelVisibility.started -= instance.OnChangePausePanelVisibility;
            @ChangePausePanelVisibility.performed -= instance.OnChangePausePanelVisibility;
            @ChangePausePanelVisibility.canceled -= instance.OnChangePausePanelVisibility;
        }

        public void RemoveCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IUIActions instance)
        {
            foreach (var item in m_Wrapper.m_UIActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UIActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public UIActions @UI => new UIActions(this);
    public interface IPlayer1Actions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnUseSpecialAbility(InputAction.CallbackContext context);
        void OnBackToCheckpoint(InputAction.CallbackContext context);
    }
    public interface IPlayer2Actions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnUseSpecialAbility(InputAction.CallbackContext context);
        void OnBackToCheckpoint(InputAction.CallbackContext context);
    }
    public interface IUIActions
    {
        void OnChangePausePanelVisibility(InputAction.CallbackContext context);
    }
}
